import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Heading, Paragraph, Caption, Code } from './index';
import { Box } from '../../Layout';
export default {
    title: 'Foundation/Typography',
    parameters: {
        layout: 'centered',
        viewport: 'responsive',
    },
};
const Template = () => {
    return (_jsxs(Box, Object.assign({ display: "flex", flexDirection: "row", justifyContent: "space-between" }, { children: [_jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Heading, Object.assign({ size: 900 }, { children: "Heading 900" })), _jsx(Heading, Object.assign({ size: 800 }, { children: "Heading 800" })), _jsx(Heading, Object.assign({ size: 700 }, { children: "Heading 700" })), _jsx(Heading, Object.assign({ size: 600 }, { children: "Heading 600" })), _jsx(Heading, Object.assign({ size: 500 }, { children: "Heading 500" })), _jsx(Heading, Object.assign({ size: 400 }, { children: "Heading 400" })), _jsx(Heading, Object.assign({ size: 300 }, { children: "Heading 300" })), _jsx(Heading, Object.assign({ size: 200 }, { children: "Heading 200" })), _jsx(Heading, Object.assign({ size: 100 }, { children: "Heading 100" }))] })), _jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Paragraph, Object.assign({ size: 300 }, { children: "Paragraph 300" })), _jsx(Paragraph, Object.assign({ size: 200 }, { children: "Paragraph 200" })), _jsx(Paragraph, Object.assign({ size: 100 }, { children: "Paragraph 100" }))] })), _jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Caption, Object.assign({ size: 200 }, { children: "Caption 200" })), _jsx(Caption, Object.assign({ size: 100 }, { children: "Caption 100" }))] })), _jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Code, { children: "Code Default" }), _jsx(Code, Object.assign({ variant: "minimal" }, { children: "Code Minimal" }))] }))] })));
};
export const Default = Template.bind({});
const CustomStyle = () => {
    return (_jsxs(Box, Object.assign({ display: "flex", flexDirection: "row", justifyContent: "space-between" }, { children: [_jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Heading, Object.assign({ size: 900, marginBottom: 20 }, { children: "Heading 900" })), _jsx(Heading, Object.assign({ size: 800 }, { children: "Heading 800" })), _jsx(Heading, Object.assign({ size: 700, overrideStyles: { backgroundColor: 'red' } }, { children: "Heading 700" })), _jsx(Heading, Object.assign({ size: 600 }, { children: "Heading 600" })), _jsx(Heading, Object.assign({ size: 500 }, { children: "Heading 500" })), _jsx(Heading, Object.assign({ size: 400 }, { children: "Heading 400" })), _jsx(Heading, Object.assign({ size: 300 }, { children: "Heading 300" })), _jsx(Heading, Object.assign({ size: 200 }, { children: "Heading 200" })), _jsx(Heading, Object.assign({ size: 100 }, { children: "Heading 100" }))] })), _jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Paragraph, Object.assign({ size: 300 }, { children: "Paragraph 300" })), _jsx(Paragraph, Object.assign({ size: 200, color: "Y600" }, { children: "Paragraph 200" })), _jsx(Paragraph, Object.assign({ size: 100 }, { children: "Paragraph 100" }))] })), _jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Caption, Object.assign({ size: 200 }, { children: "Caption 200" })), _jsx(Caption, Object.assign({ size: 100, marginTop: 50, color: "ChartBlue" }, { children: "Caption 100" }))] })), _jsxs(Box, Object.assign({ display: "flex", flexDirection: "column", gap: 10 }, { children: [_jsx(Code, { children: "Code Default" }), _jsx(Code, Object.assign({ variant: "minimal" }, { children: "Code Minimal" }))] }))] })));
};
export const Custom = CustomStyle.bind({});
