# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn install --frozen-lockfile
      - uses: chromaui/action-next@v1
        with:
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
        env:
          CHROMATIC_PROJECT_TOKEN: 0f5e566f065b
