# Workflow name
name: 'chromatic for pull requests (develop branch)'

on: 
    pull_request

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn install --frozen-lockfile
      - uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
          skip: ${{ github.event.pull_request.draft == true }}
